version: '3'

services:
  frontend:
    build:
      context: ./project-frontend
    depends_on:
      - backend

  backend:
    build:
      context: ./project-backend
    ports:
      - "6900:6900"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend